### ISSUE TITLE
Consider creating a PR to Laravel

### ISSUE THREAD

**Issue by thomas-alrek** [timacdonald/has-parameters#1]
This package is excellent, and I think this is something that you should consider upstreaming into Laravel.
Would you consider creating a PR? If not, I could help you do it.

**Comment by timacdonald** [comment]
Hi Thomas, glad to hear you dig it. Although I agree, I'd love to see this in core, for now I want to prove its usefulness before doing up a PR, also as this is only part one, I want to prepare the second part of the picture, which is preserving middleware argument types.

I'll most certainly look to doing a PR, but want to have some usage by projects first to ensure it is ready and robust enough to make it into core.

Thanks for checking it out. If you run into any issues, let me know!
